[theme]
background = "#8D92A8"
primary = "#434960"
secondary = "light black"
title = "#f8f8f2"
playing = "#217D65"
playing_selected = "#D0B3FA"
playing_bg = "#8D92A8"
highlight = "#f8f8f2"
highlight_bg = "#44475a"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "#434690"
statusbar_progress = "#217D65"
statusbar_bg = "#8D92A8"
cmdline = "#f8f8f2"
cmdline_bg = "#434690"
search_match = "#ff79c6"
